# Example /opt/pkg/etc/mk.conf file produced by bootstrap-pkgsrc
# Mon 23 Mar 2026 17:46:43 GMT

.ifdef BSD_PKG_MK	# begin pkgsrc settings

PKGSRC_COMPILER = clang
CC = clang
CXX = clang++
CPP = ${CC} -E
CLANGBASE = /usr
MAKE_JOBS = 10

PKG_DBDIR = /opt/pkg/pkgdb
LOCALBASE = /opt/pkg
SYSCONFBASE = /opt/pkg/etc
VARBASE = /opt/pkg/var
PKG_TOOLS_BIN = /opt/pkg/sbin
PKGINFODIR = info
PKGMANDIR = man

TOOLS_PLATFORM.sh? = /opt/pkg/bin/mksh
TOOLS_PLATFORM.awk? = /opt/pkg/bin/nawk
TOOLS_PLATFORM.sed? = /opt/pkg/bin/nbsed

ACCEPTABLE_LICENSES+ = gnu-agpl-v3

PKG_OPTIONS.fastfetch = -libdrm

.endif			# end pkgsrc settings
