audio_cache_size = 1000 #MiB

[theme]
#background = "#181818"
primary = "#F1F1F1"
secondary = "#DCDCDC"
title = "#1ED760"
playing = "#FF0000"
playing_selected = "#FF0000"
#playing_bg = "#181818"
highlight = "#000000"
highlight_bg = "#00FF00"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#000000"
statusbar_progress = "#00AC4C"
statusbar_bg = "#00AC4C"
cmdline = "#CBFFDE"
cmdline_bg = "#444444"
