;; Set up sources
(source gnu)
(source melpa)

;; Install themes
(depends-on "lush-theme")

;; Install packages
(depends-on "cask-mode")
(depends-on "cmake-mode")
(depends-on "crystal-mode")
(depends-on "dashboard")
(depends-on "dtrt-indent")
(depends-on "elcord")
(depends-on "hardcore-mode")
(depends-on "hl-todo")
(depends-on "jinx")
(depends-on "lua-mode")
(depends-on "markdown-mode")
(depends-on "markdown-preview-mode")
(depends-on "package-lint")
(depends-on "portage-modes")
(depends-on "rainbow-delimiters")
(depends-on "simple-httpd")
(depends-on "typit")
(depends-on "wc-mode")
(depends-on "ws-butler")
(depends-on "yaml-mode")