;; Set up sources
(source gnu)
(source melpa)

;; Install themes
(depends-on "lush-theme")

;; Install packages
(depends-on "cmake-mode")
(depends-on "dtrt-indent")
(depends-on "hardcore-mode")
(depends-on "hl-todo")
(depends-on "markdown-mode")
(depends-on "rainbow-delimiters")
(depends-on "simple-httpd")
(depends-on "ws-butler")
